<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo base_url(); ?>js/vendor/jquery-1.8.3.min.js"><\/script>')</script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
        <script src="<?php echo base_url(); ?>js/vendor/jquery.mousewheel.min.js"></script>
        <script src="<?php echo base_url(); ?>js/vendor/jquery.mCustomScrollbar.min.js"></script>
        <script src="<?php echo base_url(); ?>js/vendor/fancybox/jquery.fancybox.pack.js"></script>
        <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
        <script src="<?php echo base_url(); ?>js/plugins.js"></script>
        <script src="<?php echo base_url(); ?>js/bookbot.js"></script>
        <script src="<?php echo base_url(); ?>js/main.js"></script>